### ISSUE TITLE
我这里，群成员，有members是空的情况。。麻烦帮忙看下，谢谢。

### ISSUE THREAD

**Issue by twbbb** [xuxiaoxiao-xxx/ChatApi-WeChat#1]
{"isOwner":true,"members":{},"id":"@@319470acb12d1743d3a84b94b21c964b246a7355acf00a116cbce451ad222045","name":"开发","namePY":"KF","nameQP":"kaifa","avatarUrl":"https://wx2.qq.com/cgi-bin/mmwebwx-bin/webwxgetheadimg?seq=656511118&username=@@319470acb12d1743d3a84b94b21c964b246a7355acf00a116cbce451ad222045&skey=@crypt_9da061a9_e8e2b693a2e3834beba03b3a8ec60d78","contactFlag":3}

**Comment by xuxiaoxiao-xxx** [comment]
在登录后的初始化流程中，确实会出现获取到的群组没有成员的情况。这时可以尝试使用微信的API：batchgetcontact，将群组id（对应微信实体类的UserName）传入即可获取群组的信息。
    1.1.0版本还没有在WeChatClient中开放相应的public方法，下个版本会对这个问题进行修复。

**Comment by twbbb** [comment]
initial时候，判断members是空，放入contacts了。
 HashMap<String, WXGroup> userGroups = wxContacts.getGroups();
                for (Entry<String, WXGroup> entry : userGroups.entrySet())
    			{
                	WXGroup wg = entry.getValue();
                	if(wg.members.isEmpty())
                	{
                		contacts.add(new ReqBatchGetContact.Contact(wg.id, ""));
                	}
    			}
