### ISSUE TITLE
能否扩充联系人变更的字段？

### ISSUE THREAD

**Issue by Semoz** [xuxiaoxiao-xxx/ChatApi-WeChat#14]
预期功能：群成员加入时，发送欢迎语。
发现的问题：
1. 群成员改变后获得的WXContact对象只有群信息，没有用户信息
2. 因微信消息离线缓存，希望联系人变更消息加上时间戳
:octocat:

**Comment by xuxiaoxiao-xxx** [comment]
群成员改变后，获得的WXContact对象是群信息，里面的Members属性是所有群成员的部分信息。

1. 群成员加入时，会接收到一条来自该群的类型为10000的系统消息："xxx加入了群聊"。
可以监听系统消息实现发送欢迎语，要注意的是，红包消息等也属于系统消息。
2. 微信返回数据中，变更联系人的数据并不带时间戳。如果要加上时间戳的话，可以考虑这样实现。如果返回数据同时携带了其他消息，使用这个消息的时间戳，否则使用 System.currentTimeMillis() 作为时间戳

**Comment by Semoz** [comment]
1. 已验证，WXSystem可判断系统类型的消息，文字部分无解只能匹配content，目前已知群主加人、群主t人，群成员拉人，扫码入群有消息提示，其他均无。且联系人变更对于群来说只能获取群信息，如果要做的话估计只能匹配member差异
2.联系人离线消息暂不处理。

ps.因收到删除用户的联系人变更消息发现微信的一个bug，在iso版中发现，已经删除超过6年的用户，虽然在通讯列表中不存在，但是可以被搜索出来，点开后提示需要添加好友。
