### ISSUE TITLE
自动退出登陆了

### ISSUE THREAD

**Issue by twbbb** [xuxiaoxiao-xxx/ChatApi-WeChat#16]
五月 28, 2019 10:03:58 下午 me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread listen
较详细: 正在监听信息
五月 28, 2019 10:03:58 下午 me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread listen
较详细: 停止监听信息：1102
五月 28, 2019 10:03:58 下午 me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread run
较详细: 正在退出登录

**Comment by twbbb** [comment]
是不是机器人开太久了，有将近一个月

**Comment by xuxiaoxiao-xxx** [comment]
是一登录就自动退出吗，我最近登录2天左右就会掉线

**Comment by twbbb** [comment]
不是，有将近一个月，今天自动退出了，然后返回的retcode为1102

  if (rspSyncCheck.retcode > 0) {
                        LOGGER.finer(String.format("停止监听信息：%d", rspSyncCheck.retcode));
                        return null;
                    }

**Comment by twbbb** [comment]
之前也总是掉线，后面WeChatApi这里做了判断

    RspSync webwxsync() {
        XRequest request = XRequest.POST(String.format("https://%s/cgi-bin/mmwebwx-bin/webwxsync", host));
        request.query("sid", this.sid);
        request.query("skey", this.skey);
        request.query("pass_ticket", this.passticket);
        request.content(new XRequest.StringContent(XRequest.MIME_JSON, GSON.toJson(new ReqSync(new BaseRequest(uin, sid, skey), this.synckey))));
        RspSync rspSync = GSON.fromJson(XTools.http(httpOption, request).string(), RspSync.class);
        if(rspSync.SyncKey!=null&&rspSync.SyncKey.List!=null&&!rspSync.SyncKey.List.isEmpty())
        {
        	this.synckey = rspSync.SyncKey;
        }
        if(rspSync.SyncCheckKey!=null&&rspSync.SyncCheckKey.List!=null&&!rspSync.SyncCheckKey.List.isEmpty())
        {
        	this.syncCheckKey = rspSync.SyncCheckKey;
        }
        
        return rspSync;
    }

**Comment by xuxiaoxiao-xxx** [comment]
webwxsync里的判断我已经加到主干上了。
连续在线一个月算是时间比较长的了，你用的chatapi-wechat是基于哪一个版本的？

**Comment by twbbb** [comment]
基于1.1.5，改了这里，后面就稳定了。

当时回复在issue  运行久了，会卡死 #9

**Comment by xuxiaoxiao-xxx** [comment]
原因还不明确，所以暂时无法解决。后面会关注这块，先定时查看程序运行情况吧。

**Comment by twbbb** [comment]
呼呼，这个webwxsync，当时是分析过的。为空了，然后一直调webwxsync。

不过这次遇到的 停止监听信息：1102，
不知道是不是登陆太久正常下线还是什么，不知道这个1102代表什么，主要是担心以后会遇到。。。

**Comment by xuxiaoxiao-xxx** [comment]
微信源码里面只是对1102进行判断，并不能看出这个1102是啥含义。
查了一下网上旧的资料，有说是cookie值无效。
链接如下 https://www.cnblogs.com/flashsun/p/8493306.html

**Comment by xuxiaoxiao-xxx** [comment]
你自动退出登录之前，是不是很长时间（几个小时）没有收到消息

**Comment by xuxiaoxiao-xxx** [comment]
看了下网页版微信的cookie，每次接收到消息，或者发送消息。
都会更新webwx_data_ticket、wxpluginkey、wxsid、wxuin这几个cookie的过期时间。
设置为当前时间的12小时后。
所以可以定时向某个微信号发送消息，用来更新这几个cookie。
看看能否解决此问题

**Comment by twbbb** [comment]
应该不是cookie，有很多消息。

五月 28, 2019 10:03:54 下午 me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread listen
较详细: 监听2: wxAPI.syncCheckKey:1_669462005|2_669473040|3_669471818|11_669473019|201_1559052228|203_1559052196|1000_1559030980|1001_1559031202,wxAPI.synckey:1_669462005|2_669473040|3_669471818|11_669473019|201_1559052228|203_1559052196|1000_1559030980|1001_1559031202
五月 28, 2019 10:03:55 下午 me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread listen
较详细: 监听3: wxAPI.syncCheckKey:1_669462005|2_669473042|3_669471818|11_669473019|201_1559052231|203_1559052196|1000_1559030980|1001_1559031202,wxAPI.synckey:1_669462005|2_669473042|3_669471818|11_669473019|201_1559052231|203_1559052196|1000_1559030980|1001_1559031202
Hibernate: insert into wechat_message (content_file, content_link, content_text, fromuser_id, fromuser_name, message_type, msgid, timestamp, wxgroup_id, wxgroup_name) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
Hibernate: insert into wechat_message (content_file, content_link, content_text, fromuser_id, fromuser_name, message_type, msgid, timestamp, wxgroup_id, wxgroup_name) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
五月 28, 2019 10:03:55 下午 me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread listen
较详细: 正在监听信息
五月 28, 2019 10:03:57 下午 me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread listen
较详细: 监听2: wxAPI.syncCheckKey:1_669462005|2_669473042|3_669471818|11_669473019|201_1559052231|203_1559052196|1000_1559030980|1001_1559031202,wxAPI.synckey:1_669462005|2_669473042|3_669471818|11_669473019|201_1559052231|203_1559052196|1000_1559030980|1001_1559031202
五月 28, 2019 10:03:58 下午 me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread listen
较详细: 监听3: wxAPI.syncCheckKey:1_669462005|2_669473042|3_669471818|11_669473019|201_1559052231|203_1559052196|1000_1559030980|1001_1559031202,wxAPI.synckey:1_669462005|2_669473042|3_669471818|11_669473019|201_1559052231|203_1559052196|1000_1559030980|1001_1559031202
五月 28, 2019 10:03:58 下午 me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread listen
较详细: 正在监听信息
五月 28, 2019 10:03:58 下午 me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread listen
较详细: 停止监听信息：1102
五月 28, 2019 10:03:58 下午 me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread run
较详细: 正在退出登录

**Comment by twbbb** [comment]
我等下看下下次是什么情况出现的。

**Comment by xuxiaoxiao-xxx** [comment]
建议将cookie信息和WeChatApi中的几个登录参数也打印到日志中，方便查错

**Comment by twbbb** [comment]
好的

**Comment by Semoz** [comment]
我用的1.2.0版本，在家开服务器部署，稳定运行已经超过30天，从来没有断过:p
