### ISSUE TITLE
机器人发送链接

### ISSUE THREAD

**Issue by caixu52110** [xuxiaoxiao-xxx/ChatApi-WeChat#17]
求发送链接的功能 。
![image](https://user-images.githubusercontent.com/24220081/58689247-10780400-83b9-11e9-8c50-ec3c32dd38b6.png)

**Comment by xuxiaoxiao-xxx** [comment]
无法发送链接类型的消息。因为我没看到网页版微信提供了这样的接口。

可以发送带链接地址的普通文字类型消息。
