### ISSUE TITLE
怎么判定群里@自己的消息？

### ISSUE THREAD

**Issue by scorego** [xuxiaoxiao-xxx/ChatApi-WeChat#20]
看了一席WXMessage类，好像没这各字段？

**Comment by scorego** [comment]
错别字有点多。。  简而言之 就是怎么判断@自己的消息？

**Comment by xuxiaoxiao-xxx** [comment]
在消息的内容中体现的，有个@+用户昵称。但是还是没有办法区分是真正的@功能，还是打字打出来的。

**Comment by scorego** [comment]
那这样的话还要遍历整个消息来判断（不确定@+昵称是在消息的开头还是中间）。而且群聊是不是还要先获取displayname，判断有无@+displayname；当displayname为空是用username

**Comment by scorego** [comment]
不知道有没有兴趣把这个功能加到Message类里，做成一个方法，可以调用来判断是不是群聊里@自己的消息呢？ 如果引这个包需要手动实现感觉可以 就是不太优雅~

**Comment by scorego** [comment]
如果消息内容有“@displayname”/“@username”+一个空格的话应该可以确定这是at消息吧？因为如果是有个空格就一定会转换成at消息

**Comment by Semoz** [comment]
建议群内固定一个昵称，用字符串判断是否at自己，就算封装了方法也不能通用，假设你昵称中含有emoji表情那将会非常头大。。

**Comment by scorego** [comment]
感觉提供个接口好一些啊，虽然可能不适用于所有的昵称，但是至少适用于大部分无特殊符号的昵称

**Comment by xuxiaoxiao-xxx** [comment]
“如果消息内容有“@DisplayName”/“@username”+一个空格的话应该可以确定这是at消息吧？“
1. 这个不能判断，经过测试，@name之后还有消息的话会加空格，整个消息只有@name时是不加空格的，而且在文字输入框中手动输入@name并且加空格也不能被转换成@消息。
2. 而且当群里有同名的人时，光从字符串处理是无法判断@的是哪一个。
所以我还是同意Eric Zhang的做法：确保你在群里昵称唯一，并且自行实现是否是@自己的判断方法

**Comment by scorego** [comment]
再问下怎么想指定的群或好友发消息？是先看日志来获取群id吗？加不加@@？

**Comment by Semoz** [comment]
指定群我用的是 message.fromGroup.name 匹配😄

**Comment by xuxiaoxiao-xxx** [comment]
WeChatClient里提供了获取好友、群的方法。
根据name（昵称）去找到相应的好友、群，然后调用发送消息方法就行了。

发送消息的方法，将整个联系人对象传进去就行了

需要注意的就是如果有相同的名字的群，目前无法区分
有相同名字的好友，可以通过设置备注来区分

**Comment by scorego** [comment]
> 发送消息的方法，将整个联系人对象传进去就行了

我的意思不是回复消息，而是任意时间指定一个好友或群发消息。这样是需要初始化LISTENER在登录的时候把所有的群和好友存起来(比如存hashmap里），当你要发消息的时候取id发吗?

**Comment by xuxiaoxiao-xxx** [comment]
WeChatClient里提供了获取 **所有好友、群** 的方法。

需要发消息的时候根据name匹配到你要发消息的人或群

发送消息的方法需要的是联系人对象，不是id

**Comment by wht1992** [comment]
java.lang.StringIndexOutOfBoundsException: String index out of range: -7
	at java.lang.String.substring(String.java:1967)
	at me.xuxiaoxiao.chatapi.wechat.WeChatApi.webwxnewloginpage(WeChatApi.java:108)
	at me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread.login(WeChatClient.java:729)
	at me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread.run(WeChatClient.java:679)
2019-08-27 16:23:26.413 | W | Thread-0 | chatapi-wechat | 登录异常
String index out of range: -7
java.lang.String.substring(String.java:1967)
me.xuxiaoxiao.chatapi.wechat.WeChatApi.webwxnewloginpage(WeChatApi.java:108)
me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread.login(WeChatClient.java:729)
me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread.run(WeChatClient.java:679)
2019-08-27 16:23:26.413 | E | Thread-0 | chatapi-wechat | 登录出现错误：登陆异常



报错提示：<error><ret>1203</ret><message>为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>

**Comment by xuxiaoxiao-xxx** [comment]
现在新注册的微信号都登录不了网页微信了好像
