### ISSUE TITLE
有时间群消息会丢失判定

### ISSUE THREAD

**Issue by scorego** [xuxiaoxiao-xxx/ChatApi-WeChat#23]
经过一段时间的使用，发现有时候收到的群消息不能正常判定为群消息。这些消息的特点是日志里最后有"并亲了你一下".这个概率出现的还是挺高的，应该如何解决？

**Comment by scorego** [comment]
![捕获](https://user-images.githubusercontent.com/10768254/60766973-5f653780-a0e3-11e9-925d-d1a192e7743f.PNG)

**Comment by xuxiaoxiao-xxx** [comment]
1.在微信移动端的表现形式是什么样的
2.能否把完整的消息json对象贴出来

**Comment by scorego** [comment]
就是普通的群消息。
完整的json对象和其他消息没区别，只是后面多了“并亲你一下”几个字。
有机会我贴几个json

**Comment by scorego** [comment]
`12:55:12.422 [Thread-0] INFO main.WechatBot - 获取到消息：{"id":8062302925280647759,"idLocal":8062302925280647759,"timestamp":1562734485000,

"fromGroup":{
"isDetail":true,
"isOwner":false,
"members":{ },
"id":"@@800507277b17b0bd11af415fb9a39823e9992ace38734e6c3663e6991c044754",
"name":"EverydayWechat 交流群",
"namePY":"EVERYDAYWECHATJLQ","nameQP":"EverydayWechatjiaoliuqun","avatarUrl":"https://wx2.qq.com/cgi-bin/mmwebwx-bin/webwxgetheadimg?seq=683035299&username=@@800507277b17b0bd11af415fb9a39823e9992ace38734e6c3663e6991c044754&skey=","contactFlag":2},

"toContact":{"gender":1,"signature":"不要丧失希望。","remark":"","remarkPY":"","remarkQP":"","province":"","city":"","verifyFlag":0,"id":"@ad9ce7ad6627cfdb1e63bbe205c3d63129a736a8a7d6172d99e6a25d1f97864e","name":"猫喝老鼠","namePY":"MHLS","nameQP":"maohelaoshu","avatarUrl":"https://wx2.qq.com/cgi-bin/mmwebwx-bin/webwxgeticon?seq=638141682&username=@ad9ce7ad6627cfdb1e63bbe205c3d63129a736a8a7d6172d99e6a25d1f97864e&skey=@crypt_5b537115_ab6e934f15cf3cf56d77b4d9ba98edac","contactFlag":1},

"content":"？？？"}`

**Comment by scorego** [comment]
上面就是个例子，我把群member去掉了

**Comment by xuxiaoxiao-xxx** [comment]
fromGroup不为null，可以判断出是群消息啊

**Comment by scorego** [comment]
是的，但是日志表明这条消息没被判为群消息。我的代码在 https://github.com/scorego/WechatRobot
，入口是https://github.com/scorego/WechatRobot/blob/master/src/main/java/main/WechatBot.java

**Comment by xuxiaoxiao-xxx** [comment]
你的这条消息，没有fromUser，导致判断条件不成立。是群内成员发送的消息，还是系统消息？
如果是群内成员发送的，就有bug，需要在WechatClient类中的parseCommon方法将其AddMsg参数打印出来，详细分析fromUser没有获取到的原因

**Comment by xuxiaoxiao-xxx** [comment]
可能是某个群成员昵称或名片设置了特殊字符导致的。
参考下面这篇文章：https://zhidao.baidu.com/question/461165321224198365.html

**Comment by scorego** [comment]
好的 我看一看。
另外，感觉这个现象在程序刚启动时发生概率很高。有时候同一个人的消息，刚启动时会丢失判定，等一会之后恢复正常。
