### ISSUE TITLE
页面

### ISSUE THREAD

**Issue by zhoufu0201** [xuxiaoxiao-xxx/ChatApi-WeChat#24]
既然是网页版的  怎么没有页面啊   博主能把前端的元素添加上吗  我WX13703649180   想请教你一些问题
谢谢

**Comment by xuxiaoxiao-xxx** [comment]
1.只是使用了网页版微信的接口，如果需要页面。可以直接使用网页版微信啊。
2.有什么问题，直接在issue里面提就可以了。
