### ISSUE TITLE
我新建了一个群，但是数据那里显示不是群主。

### ISSUE THREAD

**Issue by twbbb** [xuxiaoxiao-xxx/ChatApi-WeChat#4]
我新建了一个群，但是数据那里显示不是群主。
wxText.fromGroup.isOwner 为false。

然后发现，建了几次群，然后把群删掉退出，然后多了很多没名称的群。

**Comment by twbbb** [comment]
在变更联系人这里，isOwner 取出来都是false。然后isOwner 被改了。

for (RspInit.User user : rspSync.ModContactList)
							{
								LOGGER.finer(String.format("变更联系人（%s）", user.UserName));
								wxContacts.putContact(wxAPI.host, user);
								wxListener.onModContact();
							}

**Comment by xuxiaoxiao-xxx** [comment]
1. 删除群和退出群，并不代表群解散。群名称在没有修改过的情况下就是空字符串，可以根据根据群成员的昵称生成群名称。
2. isOwner是监听到变更联系人时，使用了不全面的群信息更新联系人缓存导致的。1.1.2版本已经修复此bug并且对联系人信息维护的流程进行了优化

**Comment by twbbb** [comment]
好的，谢谢
